########################################################################################################################
############################################ simulation configuration ##################################################
########################################################################################################################

simulation:

  type: sim                                 # type of simulation to be run
                                            # options:
                                            #   - sim: full-speed simulation (for research purposes)
                                            #   - TODO: rts: real-time simulation (for HiL/real-life purposes)

  sim:                                    # settings that apply to full-speed simulations (sim)
    start: 2021-03-24T00:00:00+01:00      # start of simulation in unix time with timezone information
                                          # format (ISO 8601): %Y-%m-%dT%H:%M:%S%z (YYYY-MM-DDTHH:MM:SS+HH:MM)

    duration: 3                           # duration of the simulation
                                          # unit: days

  rts:                                    # settings that apply to real-time simulations (rts)
    start_steps: 6                        # steps to be calculated before starting the real-time simulation
                                            # note: when beginning an rts, these many steps will be simulated at an
                                            #   accelerated rate, before the rts commences, to ensure a smooth start-up

  location:                               # location of the simulation
    name: Munich                          # name of the location
                                          # note: used for naming the results

    latitude: 48.137154                   # latitude
                                          # unit: degrees

    longitude: 11.576124                  # longitude
                                          # unit: degrees

    altitude: 520                         # altitude
                                          # unit: meters

    weather: weather.ft                   # weather file to be used for the location
                                          # file types: csv, ft

  paths:                                    # paths relevant for the simulation
    input: ../03 - input_data                    # path that contains the input data
                                            # note: relative to the lemlab repository

    scenarios: ../04 - scenarios            # path that contains the scenario setup
                                            # note: relative to the lemlab repository

    results: ../05 - results                     # path that contains the scenario results
                                            # note: relative to the lemlab repository

  modeling:                                 # modeling settings
    language: pyomo                         # modeling language to be used
                                            # options:
                                            #   - jump: recommended
                                            #   - pyomo
                                            #   - linopy

    solver: gurobi                          # solver for the simulation
                                            # options (preferably MIQP capable):
                                            #   - gurobi: recommended
                                            #   - cplex
                                            #   - glpk: possible with limitations; see documentation for more info

