########################################################################################################################
############################################ simulation configuration ##################################################
########################################################################################################################

simulation:
  location:                     # Location where the simulation happens (latitude, longitude, name, altitude, timezone)
    latitude: 48.137154

    longitude: 11.576124

    name: Munich

    altitude: 520

  type: sim                                 # type of simulation to be run
                                            # options:
                                            #   - sim: full-speed simulation (for research purposes)
                                            #   - TODO: rts: real-time simulation (for HiL/real-life purposes)

  timestep: 900                           # length of minimum timestep
                                          # unit: seconds
                                          # note: all other timesteps need to be multiples of this timestep, if this
                                          #   is not the case, the simulation will not run

  sim:                                    # settings that apply to full-speed simulations (sim)
    start: 2021-03-24T00:00:00+01:00      # start of simulation in unix time with timezone information
                                          # format (ISO 8601): %Y-%m-%dT%H:%M:%S%z (YYYY-MM-DDTHH:MM:SS+HH:MM)

    duration: 3                           # duration of the simulation
                                          # unit: days

  rts:                                    # settings that apply to real-time simulations (rts)
    start_steps: 6                        # steps to be calculated before starting the real-time simulation
                                            # note: when beginning an rts, these many steps will be simulated at an
                                            #   accelerated rate, before the rts commences, to ensure a smooth start up

  weather: weather.csv                       # weather file to be used for entire region
                                            # file types: csv, ft

  paths:                                    # paths relevant for the simulation
    input: ../03 - input_data                    # path that contains the input data
                                            # note: relative to the lemlab repository

    scenarios: ../04 - scenarios            # path that contains the scenario setup
                                            # note: relative to the lemlab repository

    results: ../05 - results                     # path that contains the scenario results
                                            # note: relative to the lemlab repository

  solver: gurobi                            # solver for the simulation
                                            # options (preferably MIQP capable):
                                            #   - gurobi: recommended
                                            #   - cplex
                                            #   - glpk: possible with limitations; see documentation for more info
                                            # note: needs to be pyomo compatible

########################################################################################################################
############################################### database configuration #################################################
########################################################################################################################

database:                                   # database connection information
  admin: {user: admin_lem,
          pw: admin,
          host: 127.0.0.1,
          port: '5432',
          db: postgres,
         }

  user: {user: market_participant,
         pw: user,
         host: 127.0.0.1,
         port: '5432',
         db: postgres,
        }
