########################################################################################################################
################################################# grid configuration ###################################################
########################################################################################################################

grids:
  electricity_01:
    active: False

    creation: file                        # grid creation method
                                          # options:
                                          #   - file: create grid from 'grid.xlsx'
                                          # TODO: Create automatic grid generator, e.g. based on Kerber grids

  heat_01:
    active: False

  hydrogen_01:
    active: False